### ISSUE TITLE
Filter with match example?

### ISSUE THREAD

**Issue by hengestone** [grandquista/Lua-ReQL#10]
Any hints on the syntax for doing a filter with a function, e.g. match? The docs still refer to the ruby implementation I think.

Thanks!

**Comment by grandquista** [comment]
There is an example at https://github.com/grandquista/Lua-ReQL/blob/master/spec/changefeeds_spec.lua#L54 until I can get time to update the wiki.

**Comment by hengestone** [comment]
Great, thanks!
