### ISSUE TITLE
Module 'reql/class' not found

### ISSUE THREAD

**Issue by brianhiss** [grandquista/Lua-ReQL#14]
I've been trying to install Lua-ReQL for a few hours now in a clean VirtualBox environment and I come up with the same error: `/usr/local/share/lua/5.1/rethinkdb.lua:1: module 'reql/class' not found:`

My setup is a clean `ubuntu/trusty64` box, then install:
```shell
apt-get install -y git lua5.1 luarocks
luarocks install luabitop
luarocks install lua-reql
```

```shell
vagrant@or:/usr/local/share/lua$ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> local r=require'rethinkdb'
/usr/local/share/lua/5.1/rethinkdb.lua:1: module 'reql/class' not found:
	no field package.preload['reql/class']
	no file './reql/class.lua'
	no file '/usr/local/share/lua/5.1/reql/class.lua'
	no file '/usr/local/share/lua/5.1/reql/class/init.lua'
	no file '/usr/local/lib/lua/5.1/reql/class.lua'
	no file '/usr/local/lib/lua/5.1/reql/class/init.lua'
	no file '/usr/share/lua/5.1/reql/class.lua'
	no file '/usr/share/lua/5.1/reql/class/init.lua'
	no file './reql/class.so'
	no file '/usr/local/lib/lua/5.1/reql/class.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/reql/class.so'
	no file '/usr/lib/lua/5.1/reql/class.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/rethinkdb.lua:1: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: ?
```

```shell
vagrant@or:/usr/local/share/lua$ luarocks list

Installed rocks:
----------------

lpeg
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

lua-reql
   0.7-0 (installed) - /usr/local/lib/luarocks/rocks

luabitop
   1.0.2-3 (installed) - /usr/local/lib/luarocks/rocks

luajson
   1.3.3-1 (installed) - /usr/local/lib/luarocks/rocks

luasocket
   3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks
```

Any thoughts?

**Comment by grandquista** [comment]
There is a mismatch here [https://luarocks.org/modules/grandquista/lua-reql/0.7-0](https://luarocks.org/modules/grandquista/lua-reql/0.7-0) between the two files I uploaded. The rockspec is correct and references `tag v0.7.0`. The packed `.src.rock` has the rockspec and files from `branch v0.7.0`.

It's a quick fix. Unfortunately I won't be able to upload v0.7.1 until around 5pm PDT.

Checking out tag v0.7.0 and installing with `luarocks make` is what I was doing back then. I'm going to leave this open until v1.0.0 as a reminder to add some CI processes that can catch this.

**Comment by grandquista** [comment]
I have tested a clean install and `require` of `v0.7.1`.

**Comment by brianhiss** [comment]
Upgrading to `v0.7.1` fixed the issue. Thank you.

**Comment by grandquista** [comment]
I am moving forward with a nightly build job for travis using [coderanger/nightlies](https://github.com/coderanger/nightlies). Configuration will need to be added to busted testing to target released versions.

**Comment by grandquista** [comment]
This is complete in (grandquista/Lua-ReQL-nightly)[https://github.com/grandquista/Lua-ReQL-nightly]. Improvements to the luarocks add-on system could improve the solution. They are outside this issue and I will try to get keplerproject/luarocks#395 merged.
