### ISSUE TITLE
Problem opening RethinkDB connection from OpenResty

### ISSUE THREAD

**Issue by douglasgoodwin** [grandquista/Lua-ReQL#19]
Here is the error emitted by NGINX/OpenResty 

```
2016/08/25 22:32:09 [error] 14428#0: *32 lua entry thread aborted: runtime error: 
       /usr/local/share/lua/5.1/rethinkdb/internal/socket.lua:16: ngx.socket settimout: 
       expecting at least 2 arguments (including the object) but seen 3

stack traceback:
coroutine 0:
        [C]: in function 'settimeout'
        /usr/local/share/lua/5.1/rethinkdb/internal/socket.lua:16: in function 'socket'
        /usr/local/share/lua/5.1/rethinkdb/connection_instance.lua:213: in function 'connect'
        /usr/local/share/lua/5.1/rethinkdb/connector.lua:67: in function 'connect'
        /etc/nginx/scripts//recordTrip.lua:47: in function 'record'
        access_by_lua(otp:4):1: in function <access_by_lua(otp:4):1>, client: 12.9.33.241, 
               server: otp.metroservices.io, request: "GET /otp/routers/default/plan?arriveBy=false&date=08-25-2016&fromPlace=34.0558614843562,-118.23363006489531&maxWalkDistance=1609.34&mode=WALK,BUS,TRAINISH,CAR_PARK&num
```

**Comment by grandquista** [comment]
> expecting at least 2 arguments (including the object) but seen 3

Is enough to solve the immediate issue. The phase is unusual, but I'm almost certain it expects exactly 2 arguments.

Luasocket accepts a 3rd argument that modifies the timeout behavior slightly. I started using it to test some old timing issues and it never broke the CI.

This leads to the bigger issue that the CI does not run the nginx integration tests. #18 is fixing that.

After that I will remove the extra argument and clean up any other bugs the integration uncovers.

**Comment by grandquista** [comment]
v1.0.2 is based on local testing. Getting OpenResty integrated into the CI will be this weekend's project.

**Comment by douglasgoodwin** [comment]
Thanks, @grandquista . 
I updated the driver to lua-reql-1.0.2-0 and received a new error. hth.

```
2016/08/26 17:49:08 [error] 9733#0: *96 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/rethinkdb/reql.lua:343: attempt to index local 'connection' (a nil value)
stack traceback:
coroutine 0:
       	/usr/local/share/lua/5.1/rethinkdb/reql.lua: in function 'run'
       	access_by_lua(otp:116):68: in function <access_by_lua(otp:116):1>, client: 12.9.33.241, server: otp.metroservices.io, request: "GET /args?arriveBy=false&date=08-26-2016&fromPlace=34.0556349908537,-118.23319101989136&maxWalkDistance=1609.34&mode=WALK,BUS,TRAINISH&numItineraries=3&showIntermediateStops=true&time=10:47am&toPlace=34.0730424,-118.44690120000001&wheelchair=false HTTP/1.1", host: "otp.metroservices.io"
```

**Comment by grandquista** [comment]
I left a comment on the shared code to make this error message more useful.

**Comment by grandquista** [comment]
I am working on Docker images to test this on the nightly builder. This should be better than the mess I am making of Travis configuration here.

**Comment by grandquista** [comment]
This is the current state of the Dockerfile I am working on.

```
FROM openresty/openresty:latest

MAINTAINER Adam Grandquist <grandquista@gmail.com>

RUN apk update
RUN apk add --no-cache build-base openssl-dev perl

RUN wget http://keplerproject.github.io/luarocks/releases/luarocks-2.3.0.tar.gz
RUN tar -xf luarocks-2.3.0.tar.gz
RUN cd luarocks-2.3.0 && ./configure --with-lua="/usr/local/openresty/luajit/" --lua-suffix="jit" --with-lua-include="/usr/local/openresty/luajit/include/luajit-2.1"
RUN cd luarocks-2.3.0 && make
RUN cd luarocks-2.3.0 && make bootstrap

RUN luarocks install luasec
RUN luarocks install luacrypto
RUN luarocks install Lua-ReQL

RUN cpan CPAN
RUN cpan App::cpanminus
RUN cpanm -v --notest Test::Nginx::Socket

ADD t t

RUN prove -r t
```

I will be deploying this to the nightly build repository soon. This will improve the tests there and provide rolling feedback on integrations like OpenResty.

**Comment by grandquista** [comment]
Sorting this out is giving me a clear picture of why there are duplicate modules for each Lua platform. I still intend to support all of Lua/Luajit/Nginx/Openresty with v1.0.z, but there isn't a clear deadline I can make at this moment.

**Comment by seddonm1** [comment]
@grandquista 
I am also having trouble with the connection from OpenResty to RethinkDB. Im running some basic code to see what is going on and I am not seeing anything from the driver. When i run the code below i see only:

```sh
connect
done
```

I can't see any error messages/logs.

```lua
        location = /test {
            content_by_lua "
                local r = require 'rethinkdb'
                ngx.say('connect')

                r.connect(function(err, c)
                  if err then
                    ngx.say('error')
                    error(err.message())
                  end

                  ngx.say('connected')
                end)

                ngx.say('done')
            ";
        }
```

**Comment by grandquista** [comment]
Looks like I broke callbacks receiving errors in July here [https://github.com/grandquista/Lua-ReQL/blob/master/src/rethinkdb/connection_instance.lua#L211](https://github.com/grandquista/Lua-ReQL/blob/master/src/rethinkdb/connection_instance.lua#L211). I am going to be away from the internet for the rest of the week so I can't fix this until Sunday. A work around would be to rewrite the above as

```perl
        location = /test {
            content_by_lua "
                local r = require 'rethinkdb'
                ngx.say('connect')

                local c, err = r.connect()
                if err then
                  ngx.say('error')
                  error(err.message())
                end

                ngx.say('connected')

                ngx.say('done')
            ";
        }
```

**Comment by seddonm1** [comment]
thanks @grandquista

**Comment by grandquista** [comment]
@seddonm1 I have a minimal test passing and it will be uploaded to luarocks asap. Thanks for the link to the docker file. It will be useful when I can find time to work on the platform testing.

**Comment by grandquista** [comment]
Moved to RebirthDB/rebirthdb-lua#4
