### ISSUE TITLE
Question, not issue.

### ISSUE THREAD

**Issue by DannehSC** [grandquista/Lua-ReQL#25]
Where would I find the source for `mime`, the module required in utilities?

**Comment by grandquista** [comment]
It is part of the luasocket requirement. Take a look at the following links.

[https://github.com/diegonehab/luasocket/blob/master/src/mime.lua](https://github.com/diegonehab/luasocket/blob/master/src/mime.lua)
[https://github.com/diegonehab/luasocket/blob/master/src/mime.h](https://github.com/diegonehab/luasocket/blob/master/src/mime.h)
[https://github.com/diegonehab/luasocket/blob/master/src/mime.c](https://github.com/diegonehab/luasocket/blob/master/src/mime.c)

**Comment by DannehSC** [comment]
Thanks!
