### ISSUE TITLE
RebirthDB

### ISSUE THREAD

**Issue by thelinuxlich** [grandquista/Lua-ReQL#28]
Hey, listen! I don't know if your driver already supports fully the 2.3 version, but we've forked RethinkDB to release a 2.4 version and all drivers will have separate repositories under our organization, discussion here: https://spectrum.chat/rebirthdb

So I'm inviting you to join us, there you can have more visibility for your project, what do you think?

**Comment by grandquista** [comment]
I support 1.16 to 2.3 and there is a branch around for write hooks to support 2.4. I have seen and joined spectrum, just a little busy at the moment to do much. I would prefer if this can be forked into the org and I can contribute pull requests to make luarocks point there. This way old links will still be active.

**Comment by thelinuxlich** [comment]
Anyway, I added you as member of the organization. Now I'm thinking of a standard way for everyone to mirror the docs so we can add every language to the new site.
