### ISSUE TITLE
Depends on a future version of luasocket?

### ISSUE THREAD

**Issue by sharpobject** [grandquista/Lua-ReQL#4]
```
$ luarocks install lua-reql
Installing https://rocks.moonscript.org/lua-reql-0.6-3.rockspec...
Using https://rocks.moonscript.org/lua-reql-0.6-3.rockspec... switching to 'build' mode

Missing dependencies for lua-reql:
luasocket > 3


Error: Could not satisfy dependency: luasocket > 3
$ curl https://rocks.moonscript.org/lua-reql-0.6-3.rockspec
<snip>
dependencies = {
  'lua > 5.1',
  'luasocket > 3',
  'luajson > 1.3',
}
```

Do you know where I can find luasocket > 3?

**Comment by grandquista** [comment]
That seems to have been broken by luasocket's versioning after version 3 release candidate 1. I won't have time to get a fix out until the end of the week. Installing luasocket and then removing the line from source before building lua-reql will still work.

**Comment by grandquista** [comment]
There is a new release with dependency versions better specified. I'm seeing some new trouble on my end that seems related to luarocks changing where they are hosted.

**Comment by grandquista** [comment]
I have successfully done a fresh test and install on my end for the last two versions. @sharpobject can this be confirmed on your end?

**Comment by sharpobject** [comment]
It works!

**Comment by grandquista** [comment]
Cool.
