### ISSUE TITLE
More than 200 local variables

### ISSUE THREAD

**Issue by hengestone** [grandquista/Lua-ReQL#8]
For the current master branch built from source with
luarocks make

`lua: error loading module 'rethinkdb' from file '/usr/local/share/lua/5.1/rethinkdb.lua':
	/usr/local/share/lua/5.1/rethinkdb.lua:654: main function has more than 200 local variables
`

**Comment by grandquista** [comment]
Noted. The build script needs to be changed to not make each ReQL term a global variable.

**Comment by grandquista** [comment]
This has been started. There is still a recursive reference to `r` that is not resolved in the master branch.

**Comment by hengestone** [comment]
Hi Adam,

You can also place these variables in their own table and reference them that way - have a look at my fork.

Of course you're welcome to use the changes in my fork, it contains a small fix to build.py to make paths work on python 2.7 on Ubuntu 15.10.

Cheers!
Conrad
